openapi: "3.0.2"
info:
  title: Project Apollo Rally API
  version: "1.0"
servers:
  - url: https://paracing.vercel.app/api/v1/par/

tags:
  - name: Drivers
    description: Everything about the drivers

paths:
  /drivers:
    post:
      tags:
        - Drivers
      summary: Create a new driver on PAR
      requestBody:
        required: true
        description: Use a unique identifier to create a driver in the system
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewDriver"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Driver"
          description: Driver already existed in the system

        "201":
          description: Driver has been created in the system
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Driver"

components:
  securitySchemes:
    name:
      type: apiKey
      name: AUTHORIZATION
      in: header

  schemas:
    Driver:
      type: object
      properties:
        id:
          type: string
          example: L80Amo4J8MKs
          minLength: 12
          maxLength: 12
          description: |-
            [NanoID](https://github.com/ai/nanoid?tab=readme-ov-file#nano-id)
        name:
          type: string
          example: Force
        nationality:
          type: string
          example: CA
          minLength: 2
          maxLength: 2
          description: |-
            [Alpha-2 Country Code](https://www.iban.com/country-codes)
    NewDriver:
      type: object
      required:
        - id
        - name
        - nationality
      properties:
        id:
          description: Unique identifier for the driver such as Steam ID or email
          type: string
          example: STEAM_ID_2903408943
        name:
          type: string
          example: Force
        nationality:
          type: string
          example: CA
          minLength: 2
          maxLength: 2
          description: |-
            [Alpha-2 Country Code](https://www.iban.com/country-codes)
